# Generated by Django 5.2.6 on 2025-09-15 01:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('clothing', 'Clothing'), ('accessory', 'Accessory'), ('footwear', 'Footwear'), ('other', 'Other')], default='other')),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
